nodeLinker: node-modules
installConfig:
  pnp: false
  defaultLanguage: "node"
  skipIntegrityCheck: false
  enableImmutableInstalls: false
  networkConcurrency: 20
  nodeLinker: "node-modules"
  ignoreScripts: false
  ignoreEngines: false
  force: false
  verbose: false
  frozenLockfile: false
  production: false
  preferOffline: false
  preferFrozenLockfile: false
  dev:
    nodeLinker: "node-modules"
  optional:
    nodeLinker: "node-modules"
  peer:
    nodeLinker: "node-modules"
  workspace:
    nodeLinker: "node-modules"
  sideEffectsCache:
    enable: false
  cache:
    node-modules:
      hoistingLimits:
        "@babel/*": 1
  checksumBehavior: "throw"
  resolutions:
    '**/fsevents': '2.3.2'

# Specify supported architectures
berry:
  pluginArchitecture:
    linux-x64: 'node-linux-x64.so'
    linux-arm64: 'node-linux-arm64.so'
  pluginLocations:
    node-modules: './.yarn/plugins'
