version: '3.8'
services:
  react-app:
    container_name: react-app
    volumes:
      - ../.:/app
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    # command: 'npm rebuild esbuild && yarn start'
    ports:
      - 5173:5173